import { useState, type FormEvent } from 'react'
import { ArrowRight, KeyRound, ShieldCheck } from 'lucide-react'
import { GlassCard } from '../components/GlassCard'

type LoginPageProps = { onSubmit: (email: string, password: string) => Promise<void>; error: string | null; demoAvailable: boolean }

export function LoginPage({ onSubmit, error, demoAvailable }: LoginPageProps) {
  const [email, setEmail] = useState(import.meta.env.DEV ? 'admin@laap.local' : '')
  const [password, setPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitting(true); try { await onSubmit(email, password) } finally { setSubmitting(false) } }
  return <div className="relative grid min-h-dvh place-items-center overflow-hidden px-5 py-10"><div className="ambient ambient-one" aria-hidden="true" /><div className="ambient ambient-two" aria-hidden="true" /><GlassCard className="relative w-full max-w-[430px] p-6 sm:p-8"><div className="flex items-center gap-3"><span className="brand-mark"><ShieldCheck aria-hidden="true" size={18} strokeWidth={2.2} /></span><div><p className="font-mono text-sm font-semibold tracking-[0.12em] text-slate-100">LAAP</p><p className="text-[10px] font-medium uppercase tracking-[0.17em] text-slate-500">Control center</p></div></div><div className="mt-10"><p className="eyebrow">Secure administrator access</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.045em] text-slate-100">Welcome back.</h1><p className="mt-3 text-sm leading-6 text-slate-400">Sign in to manage leases, assignments, and trusted devices.</p></div><form className="mt-8 space-y-5" onSubmit={handleSubmit}><div><label className="mb-2 block text-xs font-medium text-slate-300" htmlFor="email">Work email</label><input id="email" value={email} onChange={(event) => setEmail(event.target.value)} className="input-base h-12 w-full px-3 text-sm" type="email" autoComplete="username" required /></div><div><div className="mb-2 flex items-center justify-between"><label className="text-xs font-medium text-slate-300" htmlFor="password">Password</label><span className="text-[11px] text-slate-600">Password manager ready</span></div><div className="relative"><KeyRound aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-600" size={15} /><input id="password" value={password} onChange={(event) => setPassword(event.target.value)} className="input-base h-12 w-full px-3 pl-9 text-sm" type="password" autoComplete="current-password" required /></div></div>{error ? <p className="rounded-xl border border-rose-400/20 bg-rose-400/10 px-3 py-2.5 text-xs text-rose-200" role="alert">{error}</p> : null}<button type="submit" disabled={submitting} className="inline-flex min-h-12 w-full cursor-pointer items-center justify-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/10 text-sm font-medium text-cyan-100 transition hover:bg-cyan-300/15 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/80">{submitting ? 'Signing in…' : 'Sign in'}{!submitting ? <ArrowRight aria-hidden="true" size={16} /> : null}</button></form>{demoAvailable ? <p className="mt-5 text-center text-[11px] leading-5 text-slate-600">Local development mode signs into the seeded administrator workspace automatically.</p> : null}</GlassCard></div>
}
