import { BarChart3, ChevronDown } from 'lucide-react'
import { useState } from 'react'
import { chartSets, type ChartRange } from '../lib/data'
import { GlassCard } from './GlassCard'

export function LeaseActivityChart() {
  const [range, setRange] = useState<ChartRange>('24h')
  const chart = chartSets[range]
  return <GlassCard className="p-5 sm:p-6" aria-label="Lease activity chart">
    <div className="flex flex-wrap items-start justify-between gap-4">
      <div><div className="flex items-center gap-2"><span className="section-icon"><BarChart3 aria-hidden="true" size={16} /></span><h2 className="section-title">Lease activity</h2></div><p className="mt-2 text-xs text-slate-500">Successful account claims across your workspace</p></div>
      <button type="button" onClick={() => setRange(range === '24h' ? '7d' : range === '7d' ? '30d' : '24h')} className="select-button" aria-label="Cycle chart range"><span>{range === '24h' ? 'Last 24 hours' : range === '7d' ? 'Last 7 days' : 'Last 30 days'}</span><ChevronDown aria-hidden="true" size={14} /></button>
    </div>
    <div className="mt-5 flex items-end justify-between gap-4"><div><p className="font-mono text-[30px] font-semibold tracking-[-0.05em] text-slate-100">{chart.value}</p><p className="mt-1 inline-flex items-center gap-1.5 text-xs text-emerald-300"><span className="trend-pill">↗</span>{chart.delta}<span className="text-slate-600">vs previous period</span></p></div><div className="flex items-center gap-4 text-[10px] text-slate-500"><span className="inline-flex items-center gap-1.5"><span className="legend-dot bg-cyan-300" />Successful</span><span className="inline-flex items-center gap-1.5"><span className="legend-dot bg-slate-700" />Capacity</span></div></div>
    <div className="mt-5 overflow-hidden rounded-2xl border border-white/[0.05] bg-slate-950/25 px-2 pb-2 pt-4 sm:px-4"><svg viewBox="0 0 495 170" className="h-[170px] w-full" role="img" aria-label={`Lease activity over ${range}`} preserveAspectRatio="none"><defs><linearGradient id="leaseArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="var(--color-cyan)" stopOpacity=".25" /><stop offset="1" stopColor="var(--color-cyan)" stopOpacity="0" /></linearGradient><linearGradient id="leaseLine" x1="0" x2="1"><stop offset="0" stopColor="var(--color-accent)" /><stop offset="1" stopColor="var(--color-cyan)" /></linearGradient></defs>{[25, 60, 95, 130].map((y) => <line key={y} x1="0" x2="495" y1={y} y2={y} stroke="rgba(148,163,184,.1)" strokeDasharray="3 5" />)}<path d={chart.area} fill="url(#leaseArea)" /><polyline points={chart.points} fill="none" stroke="url(#leaseLine)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />{chart.points.split(' ').map((point) => { const [cx, cy] = point.split(','); return <circle key={point} cx={cx} cy={cy} r="3.2" fill="var(--color-canvas)" stroke="var(--color-cyan)" strokeWidth="1.5" /> })}<line x1="405" x2="405" y1="18" y2="150" stroke="rgba(103,232,249,.35)" strokeDasharray="3 4" /><circle cx="405" cy="31" r="5" fill="var(--color-cyan)" fillOpacity=".18" /><circle cx="405" cy="31" r="3" fill="var(--color-cyan)" /><rect x="371" y="0" width="68" height="25" rx="7" fill="var(--color-tooltip)" stroke="rgba(103,232,249,.22)" /><text x="405" y="16" textAnchor="middle" fill="var(--color-cyan)" fontSize="9" fontFamily="Fira Code, monospace">42 claims</text></svg><div className="mt-1 flex justify-between px-1 text-[10px] font-mono text-slate-600">{chart.labels.map((label) => <span key={label}>{label}</span>)}</div></div>
    <div className="mt-4 flex items-center gap-1 rounded-xl bg-white/[0.025] p-1" role="group" aria-label="Chart range"><span className="mr-auto px-2 text-[10px] uppercase tracking-[0.12em] text-slate-600">View</span>{(['24h', '7d', '30d'] as ChartRange[]).map((option) => <button key={option} type="button" aria-pressed={range === option} onClick={() => setRange(option)} className={`range-button ${range === option ? 'range-button-active' : ''}`}>{option}</button>)}</div>
  </GlassCard>
}
