blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Disclosure
    url: https://github.com/Kingof3O/laap/security/policy
    about: Please report sensitive security vulnerabilities privately.
